# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pod1.ui'
#
# Created: Wed Mar  4 16:04:08 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Pod1(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(506, 636)
        self.gridLayout = QtGui.QGridLayout(Form)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.groupBox = QtGui.QGroupBox(Form)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.mc1_voltage = QtGui.QLCDNumber(self.groupBox)
        self.mc1_voltage.setObjectName(_fromUtf8("mc1_voltage"))
        self.gridLayout_2.addWidget(self.mc1_voltage, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.mc1_current = QtGui.QLCDNumber(self.groupBox)
        self.mc1_current.setObjectName(_fromUtf8("mc1_current"))
        self.gridLayout_2.addWidget(self.mc1_current, 1, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)
        self.mc1_power = QtGui.QLCDNumber(self.groupBox)
        self.mc1_power.setObjectName(_fromUtf8("mc1_power"))
        self.gridLayout_2.addWidget(self.mc1_power, 2, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 1, 0, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(Form)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_7 = QtGui.QLabel(self.groupBox_3)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_4.addWidget(self.label_7, 0, 0, 1, 1)
        self.mc3_voltage = QtGui.QLCDNumber(self.groupBox_3)
        self.mc3_voltage.setObjectName(_fromUtf8("mc3_voltage"))
        self.gridLayout_4.addWidget(self.mc3_voltage, 0, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.groupBox_3)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_4.addWidget(self.label_8, 1, 0, 1, 1)
        self.mc3_current = QtGui.QLCDNumber(self.groupBox_3)
        self.mc3_current.setObjectName(_fromUtf8("mc3_current"))
        self.gridLayout_4.addWidget(self.mc3_current, 1, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.groupBox_3)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_4.addWidget(self.label_9, 2, 0, 1, 1)
        self.mc3_power = QtGui.QLCDNumber(self.groupBox_3)
        self.mc3_power.setSmallDecimalPoint(False)
        self.mc3_power.setNumDigits(5)
        self.mc3_power.setMode(QtGui.QLCDNumber.Dec)
        self.mc3_power.setSegmentStyle(QtGui.QLCDNumber.Filled)
        self.mc3_power.setProperty("intValue", 0)
        self.mc3_power.setObjectName(_fromUtf8("mc3_power"))
        self.gridLayout_4.addWidget(self.mc3_power, 2, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox_3, 2, 0, 1, 1)
        self.groupBox_4 = QtGui.QGroupBox(Form)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.mc4_voltage = QtGui.QLCDNumber(self.groupBox_4)
        self.mc4_voltage.setObjectName(_fromUtf8("mc4_voltage"))
        self.gridLayout_5.addWidget(self.mc4_voltage, 0, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.groupBox_4)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_5.addWidget(self.label_11, 1, 0, 1, 1)
        self.mc4_current = QtGui.QLCDNumber(self.groupBox_4)
        self.mc4_current.setObjectName(_fromUtf8("mc4_current"))
        self.gridLayout_5.addWidget(self.mc4_current, 1, 1, 1, 1)
        self.label_12 = QtGui.QLabel(self.groupBox_4)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_5.addWidget(self.label_12, 2, 0, 1, 1)
        self.mc4_power = QtGui.QLCDNumber(self.groupBox_4)
        self.mc4_power.setObjectName(_fromUtf8("mc4_power"))
        self.gridLayout_5.addWidget(self.mc4_power, 2, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.groupBox_4)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_5.addWidget(self.label_10, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_4, 2, 1, 1, 1)
        self.groupBox_5 = QtGui.QGroupBox(Form)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBox_5)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.label_13 = QtGui.QLabel(self.groupBox_5)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_6.addWidget(self.label_13, 0, 0, 1, 1)
        self.mc5_voltage = QtGui.QLCDNumber(self.groupBox_5)
        self.mc5_voltage.setObjectName(_fromUtf8("mc5_voltage"))
        self.gridLayout_6.addWidget(self.mc5_voltage, 0, 1, 1, 1)
        self.label_14 = QtGui.QLabel(self.groupBox_5)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_6.addWidget(self.label_14, 1, 0, 1, 1)
        self.mc5_current = QtGui.QLCDNumber(self.groupBox_5)
        self.mc5_current.setObjectName(_fromUtf8("mc5_current"))
        self.gridLayout_6.addWidget(self.mc5_current, 1, 1, 1, 1)
        self.label_15 = QtGui.QLabel(self.groupBox_5)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_6.addWidget(self.label_15, 2, 0, 1, 1)
        self.mc5_power = QtGui.QLCDNumber(self.groupBox_5)
        self.mc5_power.setObjectName(_fromUtf8("mc5_power"))
        self.gridLayout_6.addWidget(self.mc5_power, 2, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox_5, 3, 0, 1, 1)
        self.groupBox_6 = QtGui.QGroupBox(Form)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.gridLayout_7 = QtGui.QGridLayout(self.groupBox_6)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.label_16 = QtGui.QLabel(self.groupBox_6)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_7.addWidget(self.label_16, 0, 0, 1, 1)
        self.mc6_voltage = QtGui.QLCDNumber(self.groupBox_6)
        self.mc6_voltage.setObjectName(_fromUtf8("mc6_voltage"))
        self.gridLayout_7.addWidget(self.mc6_voltage, 0, 1, 1, 1)
        self.label_17 = QtGui.QLabel(self.groupBox_6)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_7.addWidget(self.label_17, 1, 0, 1, 1)
        self.mc6_current = QtGui.QLCDNumber(self.groupBox_6)
        self.mc6_current.setObjectName(_fromUtf8("mc6_current"))
        self.gridLayout_7.addWidget(self.mc6_current, 1, 1, 1, 1)
        self.label_18 = QtGui.QLabel(self.groupBox_6)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_7.addWidget(self.label_18, 2, 0, 1, 1)
        self.mc6_power = QtGui.QLCDNumber(self.groupBox_6)
        self.mc6_power.setObjectName(_fromUtf8("mc6_power"))
        self.gridLayout_7.addWidget(self.mc6_power, 2, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox_6, 3, 1, 1, 1)
        self.groupBox_7 = QtGui.QGroupBox(Form)
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.gridLayout_8 = QtGui.QGridLayout(self.groupBox_7)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.label_19 = QtGui.QLabel(self.groupBox_7)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_8.addWidget(self.label_19, 0, 0, 1, 1)
        self.mc7_voltage = QtGui.QLCDNumber(self.groupBox_7)
        self.mc7_voltage.setObjectName(_fromUtf8("mc7_voltage"))
        self.gridLayout_8.addWidget(self.mc7_voltage, 0, 1, 1, 1)
        self.label_20 = QtGui.QLabel(self.groupBox_7)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_8.addWidget(self.label_20, 1, 0, 1, 1)
        self.mc7_current = QtGui.QLCDNumber(self.groupBox_7)
        self.mc7_current.setObjectName(_fromUtf8("mc7_current"))
        self.gridLayout_8.addWidget(self.mc7_current, 1, 1, 1, 1)
        self.label_21 = QtGui.QLabel(self.groupBox_7)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_8.addWidget(self.label_21, 2, 0, 1, 1)
        self.mc7_power = QtGui.QLCDNumber(self.groupBox_7)
        self.mc7_power.setObjectName(_fromUtf8("mc7_power"))
        self.gridLayout_8.addWidget(self.mc7_power, 2, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox_7, 4, 0, 1, 1)
        self.groupBox_8 = QtGui.QGroupBox(Form)
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.gridLayout_9 = QtGui.QGridLayout(self.groupBox_8)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.label_22 = QtGui.QLabel(self.groupBox_8)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_9.addWidget(self.label_22, 0, 0, 1, 1)
        self.mc8_voltage = QtGui.QLCDNumber(self.groupBox_8)
        self.mc8_voltage.setObjectName(_fromUtf8("mc8_voltage"))
        self.gridLayout_9.addWidget(self.mc8_voltage, 0, 1, 1, 1)
        self.label_23 = QtGui.QLabel(self.groupBox_8)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_9.addWidget(self.label_23, 1, 0, 1, 1)
        self.mc8_current = QtGui.QLCDNumber(self.groupBox_8)
        self.mc8_current.setObjectName(_fromUtf8("mc8_current"))
        self.gridLayout_9.addWidget(self.mc8_current, 1, 1, 1, 1)
        self.label_24 = QtGui.QLabel(self.groupBox_8)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout_9.addWidget(self.label_24, 2, 0, 1, 1)
        self.mc8_power = QtGui.QLCDNumber(self.groupBox_8)
        self.mc8_power.setObjectName(_fromUtf8("mc8_power"))
        self.gridLayout_9.addWidget(self.mc8_power, 2, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox_8, 4, 1, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(Form)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_3.addWidget(self.label_5, 1, 0, 1, 1)
        self.mc2_voltage = QtGui.QLCDNumber(self.groupBox_2)
        self.mc2_voltage.setObjectName(_fromUtf8("mc2_voltage"))
        self.gridLayout_3.addWidget(self.mc2_voltage, 0, 1, 1, 1)
        self.mc2_current = QtGui.QLCDNumber(self.groupBox_2)
        self.mc2_current.setObjectName(_fromUtf8("mc2_current"))
        self.gridLayout_3.addWidget(self.mc2_current, 1, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_3.addWidget(self.label_6, 2, 0, 1, 1)
        self.mc2_power = QtGui.QLCDNumber(self.groupBox_2)
        self.mc2_power.setObjectName(_fromUtf8("mc2_power"))
        self.gridLayout_3.addWidget(self.mc2_power, 2, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_3.addWidget(self.label_4, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_2, 1, 1, 1, 1)
        self.groupBox_9 = QtGui.QGroupBox(Form)
        self.groupBox_9.setMinimumSize(QtCore.QSize(0, 60))
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.label_25 = QtGui.QLabel(self.groupBox_9)
        self.label_25.setGeometry(QtCore.QRect(20, 30, 71, 16))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.label_26 = QtGui.QLabel(self.groupBox_9)
        self.label_26.setGeometry(QtCore.QRect(270, 30, 161, 21))
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.pod1_temp = QtGui.QLCDNumber(self.groupBox_9)
        self.pod1_temp.setGeometry(QtCore.QRect(120, 30, 95, 23))
        self.pod1_temp.setObjectName(_fromUtf8("pod1_temp"))
        self.toolButton = QtGui.QToolButton(self.groupBox_9)
        self.toolButton.setGeometry(QtCore.QRect(390, 30, 27, 23))
        self.toolButton.setText(_fromUtf8(""))
        self.toolButton.setAutoRaise(False)
        self.toolButton.setObjectName(_fromUtf8("toolButton"))
        self.gridLayout.addWidget(self.groupBox_9, 0, 0, 1, 2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "POD 1", None))
        self.groupBox.setTitle(_translate("Form", "MC1", None))
        self.label.setText(_translate("Form", "Voltage [V]", None))
        self.label_2.setText(_translate("Form", "Current [mA]", None))
        self.label_3.setText(_translate("Form", "Power [W]", None))
        self.groupBox_3.setTitle(_translate("Form", "MC3", None))
        self.label_7.setText(_translate("Form", "Voltage [V]", None))
        self.label_8.setText(_translate("Form", "Current [mA]", None))
        self.label_9.setText(_translate("Form", "Power [W]", None))
        self.groupBox_4.setTitle(_translate("Form", "MC4", None))
        self.label_11.setText(_translate("Form", "Current [mA]", None))
        self.label_12.setText(_translate("Form", "Power [W]", None))
        self.label_10.setText(_translate("Form", "Voltage [V]", None))
        self.groupBox_5.setTitle(_translate("Form", "MC5", None))
        self.label_13.setText(_translate("Form", "Voltage [V]", None))
        self.label_14.setText(_translate("Form", "Current [mA]", None))
        self.label_15.setText(_translate("Form", "Power [W]", None))
        self.groupBox_6.setTitle(_translate("Form", "MC6", None))
        self.label_16.setText(_translate("Form", "Voltage [V]", None))
        self.label_17.setText(_translate("Form", "Current [mA]", None))
        self.label_18.setText(_translate("Form", "Power [W]", None))
        self.groupBox_7.setTitle(_translate("Form", "MC7", None))
        self.label_19.setText(_translate("Form", "Voltage [V]", None))
        self.label_20.setText(_translate("Form", "Current [mA]", None))
        self.label_21.setText(_translate("Form", "Power [W]", None))
        self.groupBox_8.setTitle(_translate("Form", "MC8", None))
        self.label_22.setText(_translate("Form", "Voltage [V]", None))
        self.label_23.setText(_translate("Form", "Current [mA]", None))
        self.label_24.setText(_translate("Form", "Power [W]", None))
        self.groupBox_2.setTitle(_translate("Form", "MC2", None))
        self.label_5.setText(_translate("Form", "Current [mA]", None))
        self.label_6.setText(_translate("Form", "Power [W]", None))
        self.label_4.setText(_translate("Form", "Voltage [V]", None))
        self.groupBox_9.setTitle(_translate("Form", "Sensors", None))
        self.label_25.setText(_translate("Form", "Temp. [°C]", None))
        self.label_26.setText(_translate("Form", "Hydrostat failure", None))

